# Generated by Django 5.0.1 on 2024-01-13 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="created",
            new_name="created_time",
        ),
    ]
