# Generated by Django 5.0.1 on 2024-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_service", "0002_rename_created_todo_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.DateTimeField(),
        ),
    ]
