# Generated by Django 5.0.1 on 2024-01-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_service", "0003_alter_todo_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
